import { StyleSheet } from 'react-native';

export const debitCardsStyles = StyleSheet.create({
  cardBalance: {
    fontSize: 12,
    fontWeight: '900',
    maxWidth: 118,
    textAlign: 'right',
  },
  cardBottomRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 2,
  },
  cardBrand: {
    fontSize: 18,
    fontWeight: '900',
  },
  cardChip: {
    backgroundColor: '#d1d5db',
    borderRadius: 5,
    height: 32,
    width: 44,
    zIndex: 2,
  },
  cardGlowPrimary: {
    backgroundColor: 'rgba(187,195,255,0.20)',
    borderRadius: 80,
    height: 120,
    position: 'absolute',
    right: -44,
    top: -44,
    width: 120,
  },
  cardGlowSecondary: {
    backgroundColor: 'rgba(205,189,255,0.18)',
    borderRadius: 80,
    bottom: -48,
    height: 128,
    left: -48,
    position: 'absolute',
    width: 128,
  },
  cardHolder: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.8,
    marginTop: 4,
    maxWidth: 170,
    textTransform: 'uppercase',
  },
  cardNumber: {
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: 4,
  },
  cardRail: {
    gap: 14,
    paddingRight: 20,
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 2,
  },
  cardType: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  contactless: {
    fontSize: 20,
    fontWeight: '900',
  },
  content: {
    alignSelf: 'center',
    gap: 24,
    maxWidth: 520,
    paddingHorizontal: 20,
    width: '100%',
  },
  debitCard: {
    aspectRatio: 1.586,
    borderRadius: 24,
    borderWidth: 1,
    justifyContent: 'space-between',
    overflow: 'hidden',
    padding: 20,
    width: 310,
  },
  emptyCard: {
    borderRadius: 22,
    borderWidth: 1,
    gap: 6,
    padding: 18,
  },
  emptyText: {
    fontSize: 13,
    fontWeight: '700',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '900',
  },
  fab: {
    alignItems: 'center',
    borderRadius: 28,
    bottom: 96,
    height: 56,
    justifyContent: 'center',
    position: 'absolute',
    right: 20,
    width: 56,
    zIndex: 40,
  },
  fabText: {
    fontSize: 28,
    fontWeight: '300',
    lineHeight: 28,
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  formClose: {
    fontSize: 22,
    fontWeight: '900',
  },
  formContent: {
    gap: 12,
    padding: 18,
  },
  formField: {
    borderBottomWidth: 1,
    gap: 4,
    paddingVertical: 10,
  },
  formHeader: {
    alignItems: 'center',
    borderBottomColor: 'rgba(255,255,255,0.10)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 18,
  },
  formInput: {
    fontSize: 17,
    fontWeight: '800',
    minHeight: 36,
    padding: 0,
  },
  formSectionTitle: {
    fontSize: 16,
    fontWeight: '900',
    marginTop: 6,
  },
  formSheet: {
    alignSelf: 'center',
    borderWidth: 1,
    flex: 1,
    maxWidth: 560,
    width: '100%',
  },
  formTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: '900',
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  manageActions: {
    flexDirection: 'row',
    gap: 12,
  },
  manageButton: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    minHeight: 46,
    justifyContent: 'center',
  },
  manageButtonText: {
    fontSize: 14,
    fontWeight: '900',
  },
  metricCard: {
    borderRadius: 20,
    borderWidth: 1,
    flex: 1,
    minHeight: 92,
    padding: 14,
  },
  metricLabel: {
    fontSize: 12,
    fontWeight: '800',
  },
  metricLine: {
    borderRadius: 2,
    height: 4,
    marginTop: 12,
  },
  metricValue: {
    fontSize: 22,
    fontWeight: '900',
    marginTop: 4,
  },
  metricValueSmall: {
    fontSize: 17,
    fontWeight: '900',
    marginTop: 4,
  },
  metricWide: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 18,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  miniBar: {
    borderRadius: 4,
    width: 10,
  },
  miniBars: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: 5,
    height: 64,
  },
  modalOverlay: {
    backgroundColor: 'rgba(5,4,8,0.78)',
    flex: 1,
  },
  movementAmount: {
    fontSize: 13,
    fontWeight: '900',
    maxWidth: 112,
    textAlign: 'right',
  },
  movementIcon: {
    alignItems: 'center',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  movementIconText: {
    fontSize: 18,
    fontWeight: '900',
  },
  movementRow: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  movementSubtitle: {
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  movementTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  movementTitle: {
    fontSize: 14,
    fontWeight: '900',
  },
  quickAction: {
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  quickActionIcon: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    height: 54,
    justifyContent: 'center',
    width: 54,
  },
  quickActionLabel: {
    fontSize: 10,
    fontWeight: '900',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  quickActionSymbol: {
    fontSize: 14,
    fontWeight: '900',
  },
  quickActions: {
    flexDirection: 'row',
    gap: 12,
  },
  recurringAmount: {
    fontSize: 16,
    fontWeight: '900',
  },
  recurringCard: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
  },
  recurringRight: {
    alignItems: 'flex-end',
  },
  recurringTitle: {
    fontSize: 18,
    fontWeight: '900',
    marginTop: 3,
  },
  roundButton: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  roundButtonText: {
    fontSize: 12,
    fontWeight: '900',
  },
  saveButton: {
    alignItems: 'center',
    borderRadius: 18,
    height: 56,
    justifyContent: 'center',
    margin: 18,
  },
  saveButtonText: {
    fontSize: 18,
    fontWeight: '900',
  },
  screen: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  section: {
    gap: 12,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '900',
  },
  segmentedButton: {
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    flexGrow: 1,
    minHeight: 42,
    minWidth: 74,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  segmentedRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  segmentedText: {
    fontSize: 12,
    fontWeight: '900',
  },
  statusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  statusText: {
    fontSize: 13,
    fontWeight: '700',
  },
  totalBalance: {
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 42,
    marginTop: 4,
  },
  trendBar: {
    borderRadius: 8,
    minHeight: 8,
    width: 20,
  },
  trendBars: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: 12,
    height: 122,
    justifyContent: 'space-between',
  },
  trendCard: {
    borderRadius: 24,
    borderWidth: 1,
    gap: 16,
    padding: 18,
  },
  trendColumn: {
    alignItems: 'center',
    flex: 1,
    gap: 8,
    justifyContent: 'flex-end',
  },
  trendHint: {
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  trendLabel: {
    fontSize: 9,
    fontWeight: '900',
  },
});
