export const SMARTFIN_DATABASE_NAME = 'smartfin.db';

export const SQLITE_SCHEMA_STATEMENTS: string[] = [
  'PRAGMA foreign_keys = ON;',
  `CREATE TABLE IF NOT EXISTS app_settings (
    setting_key TEXT PRIMARY KEY NOT NULL,
    setting_value TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT NOT NULL,
    currency TEXT NOT NULL,
    balance_amount REAL NOT NULL,
    debt_balance_amount REAL,
    credit_limit_amount REAL,
    institution_name TEXT,
    description TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS categories (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    macro_category TEXT NOT NULL,
    color TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS subcategories (
    id TEXT PRIMARY KEY NOT NULL,
    category_id TEXT NOT NULL,
    name TEXT NOT NULL,
    color TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id)
  );`,
  `CREATE TABLE IF NOT EXISTS merchant_mappings (
    id TEXT PRIMARY KEY NOT NULL,
    raw_merchant_text TEXT NOT NULL,
    normalized_merchant_name TEXT NOT NULL,
    category_id TEXT,
    subcategory_id TEXT,
    account_id TEXT,
    match_pattern TEXT,
    match_count INTEGER NOT NULL DEFAULT 0,
    last_matched_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (subcategory_id) REFERENCES subcategories(id),
    FOREIGN KEY (account_id) REFERENCES accounts(id)
  );`,
  `CREATE TABLE IF NOT EXISTS transactions (
    id TEXT PRIMARY KEY NOT NULL,
    amount REAL NOT NULL,
    currency TEXT NOT NULL,
    description TEXT NOT NULL,
    date TEXT NOT NULL,
    account_id TEXT NOT NULL,
    category_id TEXT,
    subcategory_id TEXT,
    type TEXT NOT NULL,
    direction TEXT NOT NULL,
    status TEXT NOT NULL,
    target_account_id TEXT,
    source_message_id TEXT,
    merchant_name TEXT,
    notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id),
    FOREIGN KEY (target_account_id) REFERENCES accounts(id),
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (subcategory_id) REFERENCES subcategories(id),
    FOREIGN KEY (source_message_id) REFERENCES raw_financial_messages(id)
  );`,
  `CREATE TABLE IF NOT EXISTS transaction_splits (
    id TEXT PRIMARY KEY NOT NULL,
    transaction_id TEXT NOT NULL,
    split_type TEXT NOT NULL,
    amount REAL NOT NULL,
    currency TEXT NOT NULL,
    category_id TEXT,
    subcategory_id TEXT,
    notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (subcategory_id) REFERENCES subcategories(id)
  );`,
  `CREATE TABLE IF NOT EXISTS raw_financial_messages (
    id TEXT PRIMARY KEY NOT NULL,
    source_type TEXT NOT NULL,
    source_app TEXT,
    sender TEXT,
    raw_text TEXT NOT NULL,
    received_at TEXT NOT NULL,
    parsed_status TEXT NOT NULL,
    parsed_amount REAL,
    parsed_currency TEXT,
    parsed_merchant_name TEXT,
    parsed_account_hint TEXT,
    parser_name TEXT,
    error_message TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS account_balance_history (
    id TEXT PRIMARY KEY NOT NULL,
    account_id TEXT NOT NULL,
    balance_amount REAL NOT NULL,
    debt_balance_amount REAL,
    currency TEXT NOT NULL,
    recorded_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS budgets (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    scope_type TEXT NOT NULL,
    scope_id TEXT,
    amount REAL NOT NULL,
    currency TEXT NOT NULL,
    period TEXT NOT NULL,
    starts_on TEXT NOT NULL,
    ends_on TEXT,
    alert_50_enabled INTEGER NOT NULL DEFAULT 1,
    alert_80_enabled INTEGER NOT NULL DEFAULT 1,
    alert_90_enabled INTEGER NOT NULL DEFAULT 1,
    alert_100_enabled INTEGER NOT NULL DEFAULT 1,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS envelopes (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    target_amount REAL,
    current_amount REAL NOT NULL DEFAULT 0,
    currency TEXT NOT NULL,
    category_id TEXT,
    priority INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id)
  );`,
  `CREATE TABLE IF NOT EXISTS envelope_movements (
    id TEXT PRIMARY KEY NOT NULL,
    envelope_id TEXT NOT NULL,
    transaction_id TEXT,
    movement_type TEXT NOT NULL,
    amount REAL NOT NULL,
    currency TEXT NOT NULL,
    notes TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (envelope_id) REFERENCES envelopes(id) ON DELETE CASCADE,
    FOREIGN KEY (transaction_id) REFERENCES transactions(id)
  );`,
  `CREATE TABLE IF NOT EXISTS recurring_subscriptions (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    merchant_name TEXT,
    amount REAL NOT NULL,
    currency TEXT NOT NULL,
    category_id TEXT,
    subcategory_id TEXT,
    account_id TEXT,
    billing_day INTEGER,
    periodicity TEXT NOT NULL,
    next_charge_date TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (subcategory_id) REFERENCES subcategories(id),
    FOREIGN KEY (account_id) REFERENCES accounts(id)
  );`,
  `CREATE TABLE IF NOT EXISTS loans (
    id TEXT PRIMARY KEY NOT NULL,
    account_id TEXT,
    name TEXT NOT NULL,
    lender_name TEXT,
    principal_amount REAL NOT NULL,
    outstanding_amount REAL NOT NULL,
    currency TEXT NOT NULL,
    annual_interest_rate REAL,
    term_months INTEGER,
    monthly_payment_amount REAL,
    start_date TEXT,
    expected_end_date TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
  );`,
  `CREATE TABLE IF NOT EXISTS amortization_schedule_items (
    id TEXT PRIMARY KEY NOT NULL,
    loan_id TEXT NOT NULL,
    installment_number INTEGER NOT NULL,
    due_date TEXT NOT NULL,
    payment_amount REAL NOT NULL,
    principal_amount REAL NOT NULL,
    interest_amount REAL NOT NULL,
    remaining_balance REAL NOT NULL,
    currency TEXT NOT NULL,
    status TEXT NOT NULL,
    transaction_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (loan_id) REFERENCES loans(id) ON DELETE CASCADE,
    FOREIGN KEY (transaction_id) REFERENCES transactions(id)
  );`,
  `CREATE TABLE IF NOT EXISTS credit_card_statements (
    id TEXT PRIMARY KEY NOT NULL,
    account_id TEXT NOT NULL,
    statement_start_date TEXT NOT NULL,
    statement_end_date TEXT NOT NULL,
    payment_due_date TEXT NOT NULL,
    total_amount REAL NOT NULL,
    minimum_payment_amount REAL,
    currency TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS installment_purchases (
    id TEXT PRIMARY KEY NOT NULL,
    transaction_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    merchant_name TEXT,
    total_amount REAL NOT NULL,
    currency TEXT NOT NULL,
    installment_count INTEGER NOT NULL,
    paid_installments INTEGER NOT NULL DEFAULT 0,
    monthly_amount REAL NOT NULL,
    first_due_date TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
  );`,
  `CREATE TABLE IF NOT EXISTS financial_goals (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    goal_type TEXT NOT NULL,
    target_amount REAL NOT NULL,
    current_amount REAL NOT NULL DEFAULT 0,
    currency TEXT NOT NULL,
    target_date TEXT,
    priority INTEGER NOT NULL DEFAULT 0,
    linked_account_id TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (linked_account_id) REFERENCES accounts(id)
  );`,
  `CREATE TABLE IF NOT EXISTS investment_assets (
    id TEXT PRIMARY KEY NOT NULL,
    account_id TEXT,
    name TEXT NOT NULL,
    asset_type TEXT NOT NULL,
    quantity REAL,
    purchase_price REAL,
    current_price REAL,
    currency TEXT NOT NULL,
    platform_name TEXT,
    acquired_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
  );`,
  `CREATE TABLE IF NOT EXISTS receipt_attachments (
    id TEXT PRIMARY KEY NOT NULL,
    transaction_id TEXT,
    local_uri TEXT NOT NULL,
    merchant_name TEXT,
    total_amount REAL,
    tax_amount REAL,
    currency TEXT,
    receipt_date TEXT,
    ocr_text TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE SET NULL
  );`,
  `CREATE TABLE IF NOT EXISTS tax_tags (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS transaction_tax_tags (
    transaction_id TEXT NOT NULL,
    tax_tag_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (transaction_id, tax_tag_id),
    FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
    FOREIGN KEY (tax_tag_id) REFERENCES tax_tags(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS cash_flow_events (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    event_type TEXT NOT NULL,
    amount REAL NOT NULL,
    currency TEXT NOT NULL,
    expected_date TEXT NOT NULL,
    account_id TEXT,
    source_entity_type TEXT,
    source_entity_id TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
  );`,
  `CREATE TABLE IF NOT EXISTS smart_alerts (
    id TEXT PRIMARY KEY NOT NULL,
    alert_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    related_entity_type TEXT,
    related_entity_id TEXT,
    status TEXT NOT NULL,
    triggered_at TEXT NOT NULL,
    resolved_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS financial_health_scores (
    id TEXT PRIMARY KEY NOT NULL,
    score INTEGER NOT NULL,
    savings_component INTEGER NOT NULL,
    debt_component INTEGER NOT NULL,
    emergency_fund_component INTEGER NOT NULL,
    credit_usage_component INTEGER NOT NULL,
    goals_component INTEGER NOT NULL,
    variable_spending_component INTEGER NOT NULL,
    calculated_at TEXT NOT NULL,
    notes TEXT,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS backup_records (
    id TEXT PRIMARY KEY NOT NULL,
    backup_type TEXT NOT NULL,
    local_uri TEXT NOT NULL,
    encrypted INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    completed_at TEXT,
    error_message TEXT
  );`,
  'CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(date);',
  'CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON transactions(account_id);',
  'CREATE INDEX IF NOT EXISTS idx_transactions_category_id ON transactions(category_id);',
  'CREATE INDEX IF NOT EXISTS idx_transactions_subcategory_id ON transactions(subcategory_id);',
  'CREATE INDEX IF NOT EXISTS idx_transactions_source_message_id ON transactions(source_message_id);',
  'CREATE UNIQUE INDEX IF NOT EXISTS idx_subcategories_category_name ON subcategories(category_id, name);',
  'CREATE INDEX IF NOT EXISTS idx_merchant_mappings_raw_text ON merchant_mappings(raw_merchant_text);',
  'CREATE INDEX IF NOT EXISTS idx_raw_financial_messages_received_at ON raw_financial_messages(received_at);',
  'CREATE INDEX IF NOT EXISTS idx_account_balance_history_account_recorded ON account_balance_history(account_id, recorded_at);',
  'CREATE INDEX IF NOT EXISTS idx_budgets_scope ON budgets(scope_type, scope_id);',
  'CREATE INDEX IF NOT EXISTS idx_envelope_movements_envelope_id ON envelope_movements(envelope_id);',
  'CREATE INDEX IF NOT EXISTS idx_recurring_subscriptions_next_charge ON recurring_subscriptions(next_charge_date);',
  'CREATE INDEX IF NOT EXISTS idx_loans_account_id ON loans(account_id);',
  'CREATE UNIQUE INDEX IF NOT EXISTS idx_amortization_loan_installment ON amortization_schedule_items(loan_id, installment_number);',
  'CREATE INDEX IF NOT EXISTS idx_credit_card_statements_account_due ON credit_card_statements(account_id, payment_due_date);',
  'CREATE INDEX IF NOT EXISTS idx_installment_purchases_account_id ON installment_purchases(account_id);',
  'CREATE INDEX IF NOT EXISTS idx_financial_goals_status ON financial_goals(status);',
  'CREATE INDEX IF NOT EXISTS idx_investment_assets_account_id ON investment_assets(account_id);',
  'CREATE INDEX IF NOT EXISTS idx_receipt_attachments_transaction_id ON receipt_attachments(transaction_id);',
  'CREATE INDEX IF NOT EXISTS idx_cash_flow_events_expected_date ON cash_flow_events(expected_date);',
  'CREATE INDEX IF NOT EXISTS idx_smart_alerts_status ON smart_alerts(status);',
  'CREATE INDEX IF NOT EXISTS idx_financial_health_scores_calculated_at ON financial_health_scores(calculated_at);',
];
